version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  streamlit:
    build: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data:
